### PR TITLE
Build from source

### LINKED ISSUE #1: Build from source
JPEXS Decompiler is free software. We could be building it from source, but we're not.

### LINKED ISSUE #2: Set up Flatpak External Data Checker
Currently, updates must be checked for and applied manually. Setting up [Flatpak External Data Checker](https://github.com/flathub/flatpak-external-data-checker) would automate this process. I'd like it to make pull requests, but not automatically merge them so they can be tested first.

### PR DESCRIPTION
**Pull request by Newbytee**
Works, but there's no .desktop file and it's version "0.0.0" according to the UI.

Closes #1 
Closes #2

### CODE REVIEW

**Comment by jindrapetrik** [comment]
If you want to build a release with specific version, you need to create a file `version.properties` with following content:
```
major=x
minor=y
release=z
build=0
revision=git_hash
debug=false
```
fill in x, y, z, git_hash - these should match version tag.

and then execute

`ant new-version`

**Comment by jindrapetrik** [comment]
Also, the `ant new-version` requires file `tools.properties` with paths to NSIS and launch4j.
For windows someting like:
```
nsis.path = c:\\Program Files (x86)\\NSIS\\
launch4j.path = c:\\Program Files (x86)\\Launch4j\\
```
For linux, I already build it on travis - the proper tools for linux are in `travis/tools` folder.
See `travis/before_install.sh` for info how to compile NSIS.

**Comment by jindrapetrik** [comment]
UPDATE: I just added new ant tasks. Now you can build releases for linux (deb) separately without need of NSIS,
You still need launch4j.
New command is
```
ant new-version-deb
```

Other tasks: new-version-osx-app-archive, new-version-installer, new-version-osx-app-installer, new-version-archive, new-version-library

**Comment by Newbytee** [comment]
Thanks for the advice! It was very helpful. It works as expected now, and this should let updates be automated. I'm thinking I'll still have them be tested manually before merging though. However, it's done in a bit of a weird way since I'm making a release archive but not actually using the release archive since using that complicates the build process. I don't think it particularly matters since this isn't included as part of the package delivered to end users anyway, but it could definitely be cleaner. However, I'm not sure how to do it better.

**Pull request merged**
