### PR TITLE
Hopefully fix audio

### PR DESCRIPTION
**Pull request by Newbytee**

### CODE REVIEW

**Comment by Zishan-Rahman** [comment]
As I said under the issue I created, the audio has been fixed. Thanks again!

**Comment by Newbytee** [comment]
Thanks for testing! I suggest you remove the test version you installed from here. It won't be updated any more since it comes from a test repo and if I'm to guess it's probably going to be the one that gets launched by default. Removing it should be enough to make Flatpak use the non-test branch again. Note that the audio fix will take a few hours to reach Flathub though.

**Comment by Zishan-Rahman** [comment]
> Note that the audio fix will take a few hours to reach Flathub though.

Ah, I was wondering why the fix wasn't showing up on the Flathub version yet. I already deleted the test build, and remotes, from my system.

Until the fix reaches Flathub, I've got the relevant PulseAudio and inter-process communications permissions enabled on Flatseal. I feel kinda stupid for not thinking of that earlier, but it's still nice to have the permissions pre-configured during the install itself.

Thanks again!

**Comment by Newbytee** [comment]
> Until the fix reaches Flathub, I've got the relevant PulseAudio and inter-process communications permissions enabled on Flatseal. I feel kinda stupid for not thinking of that earlier, but it's still nice to have the permissions pre-configured during the install itself.

It should definitely work by default, I just never messed with audio in this decompiler so I didn't notice that it was broken.

**Pull request merged**
