### PR TITLE
Update Freedesktop runtime to 23.08

### PR DESCRIPTION
**Pull request by Zishan-Rahman**

### CODE REVIEW

**Comment by Zishan-Rahman** [comment]
Ah, should've checked flathub/org.freedesktop.Sdk.Extension.openjdk8#36 first :man_facepalming:

Though [there _is_ a 23.08 branch for the JDK extension now](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/tree/branch/23.08) so this _shouldn't_ be an issue now?

To be fair, I'm not entirely sure why the build failed exactly, so I'll try it again.

bot, build

**Comment by Newbytee** [comment]
It looks to me like this is some programming error due to a typo in Flathub's Python code. `builtins.NameError: name 'downloadd_cmd' is not defined` sounds like someone accidentally wrote downloadd_cmd instead of download_cmd and then published it.

**Comment by Newbytee** [comment]
Actually, that error is just a red herring. The real problem was that the v23.08 branch of OpenJDK only was published 13 minutes ago: https://buildbot.flathub.org/#/builders/6/builds/64887

**Comment by Newbytee** [comment]
bot, build

**Comment by Newbytee** [comment]
Never mind, I got confused. It's not been published yet. We should probably try again in 3 hours or so.

**Comment by Zishan-Rahman** [comment]
Alright, time to try again now :crossed_fingers:

bot, build

**Comment by Zishan-Rahman** [comment]
It's _still_ throwing up the same `downloadd_cmd` error as before:
image

Thing is, though, [the latest version of buildbot, as of the time this comment is posted, doesn't have this typo](https://github.com/flathub/buildbot/blob/flathub/master/buildbot/flathub_master.py), and [neither does the latest tag's version of flathub_master.py](https://github.com/flathub/buildbot/blob/f6ebf18b97846042025d44b9ade46c02801915af/master/buildbot/flathub_master.py), and I'm not sure which version the _deployed_ bot is using but I haven't gotten this problem in any other buildbot test build I've done this week so far. 

So I'm not entirely sure why this is happening, but it's been a while, so I'll try this again :crossed_fingers: 

bot, build

**Comment by Zishan-Rahman** [comment]
```bash
FB: Running 'flatpak --user info runtime/org.freedesktop.Sdk/x86_64/23.08 --show-metadata' on host
FB: host_command_exited_cb 893057 0
Dependency Extension: org.freedesktop.Sdk.Extension.openjdk8 23.08
FB: Running 'flatpak --user info org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08 --show-commit' on host
error: org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08 not installed
FB: host_command_exited_cb 893060 256
Trying to install org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08 from flathub
FB: Running 'flatpak --user install -y --noninteractive flathub org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08' on host
error: Nothing matches org.freedesktop.Sdk.Extension.openjdk8 in remote flathub
FB: host_command_exited_cb 893063 256
Trying to install org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08 from flathub-beta
FB: Running 'flatpak --user install -y --noninteractive flathub-beta org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08' on host
error: Nothing matches org.freedesktop.Sdk.Extension.openjdk8 in remote flathub-beta
FB: host_command_exited_cb 893067 256
Error installing deps: running `flatpak --user install -y --noninteractive flathub org.freedesktop.Sdk.Extension.openjdk8/x86_64/23.08`: Child process exited with code 1
program finished with exit code 1
elapsedTime=4.143064
```

@Newbytee Sorry for the ping, but I'm confused regarding org.freedesktop.Sdk.Extension.openjdk8. [The runtime-specific branch _is_ there](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/tree/branch/23.08), with changes as recent as 2 days ago (as of the time this comment is posted), but there's also an open issue (flathub/org.freedesktop.Sdk.Extension.openjdk8#36) and a draft pull request (flathub/org.freedesktop.Sdk.Extension.openjdk8#37). So has the branch not been published to Flathub yet? And what else could be going wrong? :thinking:

**Comment by Newbytee** [comment]
Yeah, I don't know either. It looks like OpenJDK 8 for 23.08 should be published: https://buildbot.flathub.org/#/apps/org.freedesktop.Sdk.Extension.openjdk8~2F23.08

I'll try again. If it still doesn't work, I'll have to ask someone.

bot, build

**Comment by Newbytee** [comment]
Sorry for all the spam. The issue is that despite the 23.08 branch existing in the OpenJDK 8 Flathub repo, it's still built targeting 22.08.

**Comment by Zishan-Rahman** [comment]
So now the problem seems to be fixed on [org.freedesktop.Sdk.Extension.openjdk](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/blob/0c699e7d1670ae4af27a80aded3c65636d9187b0/org.freedesktop.Sdk.Extension.openjdk8.yaml#L4)'s end, as both the issue is closed and the pull request is merged. I think it's time we tried building this again. This time it should work :crossed_fingers: 

bot, build

**Comment by Zishan-Rahman** [comment]
> Build [65863 successful](https://buildbot.flathub.org/#/builders/6/builds/65863)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/48504/com.jpexs.decompiler.flash.flatpakref
> ```

**Finally!** :partying_face:

> Sorry for all the spam. The issue is that despite the 23.08 branch existing in the OpenJDK 8 Flathub repo, it's still built targeting 22.08.

No worries, and thanks for all your help @Newbytee (and, again, sorry for the ping)!

**Comment by Newbytee** [comment]
Works for me. Thanks for taking care of this!

**Pull request merged**
